### ISSUE TITLE
`via.hypothes.is` is on the block list for Dating

### ISSUE THREAD

**Issue by 0xedward** [olbat/ut1-blacklists#11]
NextDNS is using the [dating domains list](https://github.com/nextdns/metadata/blob/master/parentalcontrol/categories/dating.json#L4) for blocking Dating under its Parental Control setting.

`via.hypothes.is` is currently in the [domains blocklist for dating](https://github.com/olbat/ut1-blacklists/blob/master/blacklists/dating/domains). As far as I'm aware, [Hypothes.is](https://web.hypothes.is/) doesn't have anything to do with dating. 

Would we be able to remove it from `via.hypothes.is` from dating domains blocklist?

**Comment by olbat** [comment]
As mentioned on the project's README page, this repository is a read-only mirror.

I suggest you to reach out the authors of the list if you want to add new entries: http://dsi.ut-capitole.fr/blacklists/index_en.php.
