### ISSUE TITLE
Why do domain lists contain Ip addresses?

### ISSUE THREAD

**Issue by pallebone** [olbat/ut1-blacklists#28]
Hi there,

Thank you for these lists. I am wondering why some lists contain IP addresses when they are domain lists eg:
  [i] Target: https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/malware/domains
  [✓] Status: Retrieval successful
  [✓] Parsed 47624 exact domains and 0 ABP-style domains (ignored 110 non-domain entries)
      Sample of non-domain entries:
        - "1.70.140.7"
        - "102.157.7.1"
        - "103.139.242.6"
        - "103.174.104.8"
        - "104.200.72.2"

Kind regards
Peter

**Comment by pallebone** [comment]
Also this list:

  [i] Target: https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/doh/domains
  [✓] Status: Retrieval successful
  [✓] Parsed 241 exact domains and 0 ABP-style domains (ignored 5 non-domain entries)
      Sample of non-domain entries:
        - "1.0.0.1"
        - "1.1.1.1"
        - "8.8.4.4"
        - "8.8.8.8"
        - "9.9.9.9"

**Comment by pallebone** [comment]
List still has this issue.

**Comment by pallebone** [comment]
both lists.

**Comment by olbat** [comment]
This repository is only a read-only mirror. Please check [the README file](https://github.com/olbat/ut1-blacklists/blob/master/README.md) if you want to reach out to the maintainer of the lists.
