### ISSUE TITLE
coronavirus-data.com marked as malware domain

### ISSUE THREAD

**Issue by crssi** [olbat/ut1-blacklists#3]
Is the `coronavirus-data.com` really a malware distribute domain as marked at https://github.com/olbat/ut1-blacklists/blob/master/blacklists/malware/domains ?

Where is this coming from?

Thank you

**Comment by olbat** [comment]
Hello,

I do not maintain those lists, only a read-only copy of them on GitHub.
Please reach out with the maintainer to make this change (see http://dsi.ut-capitole.fr/blacklists/).

Good luck and have a nice day!

**Comment by fprigent** [comment]
So much fake and phishing coronavirus sites.
Should be corrected now. Thanks for the information.

**Comment by olbat** [comment]
No problem. Hope you'll manage to get it fixed, just in case you didn't notice, the website is also available in English: http://dsi.ut-capitole.fr/blacklists/index_en.php .
