### ISSUE TITLE
Another unknown Wangsu - CDN

### ISSUE THREAD

**Issue by WoefulWrecker** [olbat/ut1-blacklists#30]
Has nothing to do with Apple.
Came across in my blocked list, but nothing in any blacklist providers or Pi Hole.
I have combined Blacklist of over 2.5million blacklist exclude porn etc, only Ads and trackers in a text file, nothing in that file.
https://www.netify.ai/resources/domains/qtlcdn.com

“appledownload.qtlcdn.com”

Cheers

**Comment by olbat** [comment]
Please check the README file to reach out to the maintainer of this list. This repository is only a mirror.
