### ISSUE TITLE
bitbucket.org

### ISSUE THREAD

**Issue by beerisgood** [olbat/ut1-blacklists#4]
This is a false positive.

Please remove it from your
https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/malware/domains

**Comment by olbat** [comment]
Hello,

I do not maintain those lists, only a read-only copy of them on GitHub.
Please reach out with the maintainer to make this change (see http://dsi.ut-capitole.fr/blacklists/).

Good luck and have a nice day!
