### ISSUE TITLE
TikTok breakage

### ISSUE THREAD

**Issue by crssi** [olbat/ut1-blacklists#6]
On iPhone Safari (just Safari) browser there is a breakage as TikTok video does not work at
`https://m.tiktok.com/v/6883213902075759877.html?_d=secCgsIARCbDRgBIAIoARI%2BCjzUMqGXP1oASsjjyIlnH29wyckO7gvjRXgnXnXo5oa3qa0IqklLd2n2fJpJUvnFxJls3fwT%2FfDBOAH7BNwaAA%3D%3D&language=en&preview_pb=0&sec_user_id=MS4wLjABAAAA8oecaE1zBK_dC2iQmACrhuYJ4Tb99mceyDNsp8NyQgtK0GN994rUKyEVc2rGF2Gp&share_item_id=6883213902075759877&share_link_id=918F3582-D993-4839-A3B1-95932103B389&timestamp=1602885682&tt_from=sms&u_code=d4khfbf9e43ehj&user_id=6659919579957805061&utm_campaign=client_share&utm_medium=ios&utm_source=sms`

due to `sf16-muse-va.ibytedtos.com` listed in [phishing](https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/phishing/domains) and [malware](https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/malware/domains) blacklists... see also https://github.com/nextdns/metadata/issues/428#issuecomment-711028415

Thank you and cheers

**Comment by drego85** [comment]
Hi Guys,
I have whitelisted the domain from phishing.army!

At the next update it will be removed and will never be inserted.

**Comment by olbat** [comment]
This list is not maintained on GitHub, this is just a read-only mirror.

Please refer to the [README](https://github.com/olbat/ut1-blacklists/blob/master/README.md) for instructions to contact the maintainer(s) of the list.
