### ISSUE TITLE
Why is this domain listed?

### ISSUE THREAD

**Issue by Corey-Code** [olbat/ut1-blacklists#7]
https://github.com/olbat/ut1-blacklists/blob/5f5efaece2e27eaecced8d70ee9c5d886e16cf34/blacklists/cryptojacking/domains#L7848

**Comment by olbat** [comment]
This repository is a read-only mirror. If you have questions about the content of the lists, please refer to the [REAMDE file](https://github.com/olbat/ut1-blacklists).
